export interface IProduct {
  _id?: string;
  "Uniq Id"?: string;
  "Crawl Timestamp"?: string;
  "Dataset Origin"?: string;
  "Product Id"?: string;
  "Product Barcode"?: string;
  "Product Company Type Source"?: string;
  "Product Brand Source"?: string;
  "Product Brand Normalised Source"?: string;
  "Product Name Source"?: string;
  "Match Rank"?: string;
  "Match Score"?: string;
  "Match Type"?: string;
  Retailer?: string;
  "Product Category"?: string;
  "Product Brand"?: string;
  "Product Name"?: string;
  "Product Price"?: string;
  ASIN?: string;
  Upc?: string;
  "Product Url"?: string;
  Market?: string;
  "Product Description"?: string;
  "Product Currency"?: string;
  "Product Available Inventory"?: string;
  "Product Image Url"?: string;
  "Product Model Number"?: string;
  "Product Tags"?: string;
  "Product Contents"?: string;
  "Product Rating"?: string;
  "Product Reviews Count"?: string;
  Bsr?: string;
  "Joining Key"?: string;
  "Pack Size Or Quantity"?: string;
  Mrp?: string;
  "Site Name"?: string;
  Offers?: string;
  "Combo Offers"?: string;
  "Stock Availibility"?: string;
  "Product Asin"?: string;
}
