export const categories = [
  "Home",
  "Clothing, Shoes & Accessories",
  "Lighting",
  "Beauty",
  "Home Improvement",
  "Health, Household & Personal Care",
  "Kitchen & Dining",
  "Garden",
  "Baby",
  "Pet Supplies",
  "Medical Supplies & Equipment",
  "Stationery & Office Products",
  "Toys & Games",
  "Sports, Fitness & Outdoors",
  "Automotive",
  "Office Products",
  "Health & Household",
  "Small Appliance Parts & Accessories",
  "Clothing, Shoes & Jewelry",
  "Tools & Home Improvement",
  "Electronics",
  "Patio, Lawn & Garden",
  "Industrial & Scientific",
  "Sports & Outdoors",
  "Mobility & Daily Living Aids",
  "Grocery & Gourmet Food",
  "Skin Care",
  "Bath & Shower",
  "Grocery & Gourmet Foods",
  "Hair Care",
  "Fragrance",
];
